### ISSUE TITLE
Code style: use PEP 585 for `tuple` typing

### ISSUE THREAD

**Issue by CommanderTvis** [breandan/picograd#1]

**Comment by breandan** [comment]
Looking at the [`tuple` typing](https://docs.python.org/3/library/typing.html#typing.Tuple) docs in PEP 585, there's a few ways we could use it. What specifically did you have in mind?

**Comment by CommanderTvis** [comment]
> Looking at the [`tuple` typing](https://docs.python.org/3/library/typing.html#typing.Tuple) docs in PEP 585, there's a few ways we could use it. What specifically did you have in mind?

Replace `Tuple[T]` with `tuple[T]`.

**Comment by breandan** [comment]
I see. BTW [ktuples](https://github.com/vorpal-research/ktuples) looks interesting. Maybe it could be useful for KMath.

**Comment by CommanderTvis** [comment]
> I see. BTW [ktuples](https://github.com/vorpal-research/ktuples) looks interesting. Maybe it could be useful for KMath.

We always use `data class` instead of tuples with length more than 3.
